# Generated by Django 5.2.7 on 2025-12-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
