# Generated by Django 5.2.7 on 2025-12-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_extraction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='MedExtractor/'),
        ),
    ]
