# Generated by Django 5.2.7 on 2025-12-22 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_extraction_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
