# Generated by Django 5.2.6 on 2025-10-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchronic',
            name='severity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
