# Generated by Django 5.2.6 on 2025-10-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userchronic_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userallergy',
            name='reaction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
