# Generated by Django 5.2.6 on 2025-11-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userallergy_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usermedication',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
