# Generated by Django 5.2.6 on 2025-11-05 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_medication_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['next_due', '-created_at']},
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='message',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_datetime',
        ),
        migrations.AddField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='frequency',
            field=models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='next_due',
            field=models.DateTimeField(blank=True, help_text='Next scheduled datetime (timezone-aware)', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default='08:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='title',
            field=models.CharField(default='Reminder', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.CharField(choices=[('medication', 'Medication'), ('monitoring', 'Health Monitoring'), ('appointment', 'Appointment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
    ]
