# Generated by Django 5.2.6 on 2025-11-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_blood_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blood_type',
        ),
    ]
