# Generated by Django 5.2.6 on 2025-11-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
