# Generated by Django 5.2.6 on 2025-11-14 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_is_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharinglog',
            name='is_shared_with',
        ),
        migrations.RemoveField(
            model_name='usercareprovider',
            name='care_provider',
        ),
        migrations.RemoveField(
            model_name='sharinglog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercareprovider',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='provider_contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scope', models.CharField(default='full', max_length=32)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants_made', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider', 'data_scope')},
            },
        ),
        migrations.CreateModel(
            name='SharingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scope', models.CharField(choices=[('full', 'Full')], default='full', max_length=32)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_provider', 'data_scope')},
            },
        ),
        migrations.DeleteModel(
            name='AccessLog',
        ),
        migrations.DeleteModel(
            name='CareProvider',
        ),
        migrations.DeleteModel(
            name='SharingLog',
        ),
        migrations.DeleteModel(
            name='UserCareProvider',
        ),
    ]
