# Generated by Django 5.2.6 on 2025-11-21 11:23

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_sharinglog_is_shared_with_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalfile',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='category',
            field=models.CharField(default='Document', max_length=50),
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='file',
            field=models.FileField(default='1', upload_to=user.models.medical_file_upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='medical_files/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
