# Generated by Django 5.2.6 on 2025-11-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['next_due', 'time', 'title']},
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='date',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('once', 'One-time')], default='daily', max_length=16),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='next_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.CharField(choices=[('medication', 'Medication'), ('monitoring', 'Health Monitoring'), ('appointment', 'Appointment')], default='medication', max_length=32),
        ),
    ]
