# Generated by Django 5.2.6 on 2025-12-02 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usermedication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
