# Generated by Django 5.2.6 on 2025-12-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_accessgrant_created_at_accessgrant_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
