# Generated by Django 5.2.6 on 2025-12-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_user_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='weight',
            field=models.CharField(blank=True, null=True),
        ),
    ]
