# Generated by Django 5.2.7 on 2025-12-07 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_user_height_alter_vitalsign_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyhistory',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='relative',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='age_of_onset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='condition',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='relationship',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
