# Generated by Django 5.2.7 on 2025-12-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_familyhistory_disease_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyhistory',
            old_name='note',
            new_name='notes',
        ),
    ]
