# Generated by Django 5.2.6 on 2025-12-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_rename_note_familyhistory_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogProxy',
            fields=[
            ],
            options={
                'verbose_name': '📋 Activity Log Dashboard',
                'verbose_name_plural': '📋 Activity Log Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.activitylog',),
        ),
        migrations.AddField(
            model_name='sharingrequest',
            name='alergys',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharingrequest',
            name='desises',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharingrequest',
            name='family',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharingrequest',
            name='fiels',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharingrequest',
            name='madactions',
            field=models.BooleanField(default=True),
        ),
    ]
