# Generated by Django 5.2.6 on 2025-12-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_activitylogproxy_sharingrequest_alergys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgrant',
            name='alergys',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='desises',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='family',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='fiels',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='madactions',
            field=models.BooleanField(default=True),
        ),
    ]
