# Generated by Django 5.2.7 on 2025-12-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_accessgrant_alergys_accessgrant_desises_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylogproxy',
            options={'verbose_name': 'Activity Log Dashboard', 'verbose_name_plural': 'Activity Log Dashboard'},
        ),
    ]
