# Generated by Django 5.2.7 on 2025-12-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_activitylogproxy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgrant',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
