# Generated by Django 5.2.7 on 2025-12-19 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_accessgrant_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessgrant',
            name='permissions',
        ),
    ]
