# Generated by Django 5.2.7 on 2025-12-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_remove_accessgrant_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
