# Generated by Django 5.2.7 on 2025-12-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
    ]
