# Generated by Django 5.2.7 on 2025-12-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_remove_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='next_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
