# Generated by Django 5.2.7 on 2025-12-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_alter_reminder_next_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='next_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
