# Generated by Django 5.2.6 on 2026-01-02 08:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_rename_email_verified_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailotp',
            name='user_emailo_user_id_7d5bb5_idx',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='code',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='uuid',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(db_index=True, default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailotp',
            name='otp_hash',
            field=models.CharField(default='timezone.now', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email'], name='user_emailo_email_d0a966_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['created_at'], name='user_emailo_created_8ad060_idx'),
        ),
    ]
