# Generated by Django 5.2.7 on 2026-01-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_remove_emailotp_user_emailo_user_id_7d5bb5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchronic',
            name='date_diagnosed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
