# Generated by Django 5.2.6 on 2026-01-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_alter_userchronic_date_diagnosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingrequest',
            name='reactivates_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
