# Generated by Django 5.2.6 on 2026-01-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_sharingrequest_reactivates_hidden'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharingrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sharingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='sharingrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_user', 'to_provider', 'data_scope'), name='uniq_pending_request_per_scope'),
        ),
    ]
