# Generated by Django 5.2.6 on 2026-01-17 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_alter_sharingrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
